### ISSUE TITLE
admin?

### ISSUE THREAD

**Issue by tmcw** [inkwell/inkwell.github.com#2]
@dhcole can you give me admin to this repo/org to make branches locally? thx!

**Comment by dhcole** [comment]
y, working on it. Need to get access myself, so I contacted github support.

**Comment by tmcw** [comment]
ha, then who _does_ have access?

**Comment by dhcole** [comment]
For some reason I made it as a new account instead of an organization. Just figured it out though and converted it to an org. You should have an email update.
